---
- name: Check current node_exporter version.
  command: "{{ node_exporter_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: node_exporter_version_check

- name: Configure latest version
  include_tasks: config-version.yaml
  when: >
    node_exporter_version is match("latest")
    or node_exporter_version is not defined

- name: Download and unarchive node_exporter into temporary location.
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /tmp
    remote_src: true
    mode: 0755
  when: >
    node_exporter_version_check.stdout is not defined
    or node_exporter_version not in node_exporter_version_check.stdout
  register: node_exporter_download_check

- name: Move node_exporter binary into place.
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}/node_exporter"
    dest: "{{ node_exporter_bin_path }}"
    mode: 0755
    remote_src: true
  notify: restart node_exporter
  when: >
    node_exporter_download_check is changed
    or node_exporter_version_check.stdout | length == 0

- name: Create node_exporter group (optional fixed GID)
  ansible.builtin.group:
    name: node_exporter
    gid: "{{ node_exporter_gid | default(omit) }}"
    state: present
  when: "node_exporter_gid is defined"

- name: Create node_exporter user (optional fixed UID)
  user:
    name: node_exporter
    shell: /sbin/nologin
    create_home: false
    uid: "{{ node_exporter_uid | default(omit) }}"
    group: "{{ (node_exporter_gid is defined) | ternary('node_exporter', omit) }}"
    state: present

- name: Copy the node_exporter systemd unit file.
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
  register: node_exporter_service
  notify: restart node_exporter

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  when: node_exporter_service is changed

- name: Ensure node_exporter is running and enabled at boot.
  service:
    name: node_exporter
    state: "{{ node_exporter_state }}"
    enabled: "{{ node_exporter_enabled }}"

- name: Verify node_exporter is responding to requests.
  uri:
    url: "http://{% if node_exporter_host !='' %}{{ node_exporter_host }}{% else %}localhost{% endif %}:{{ node_exporter_port }}/"
    return_content: true
  register: metrics_output
  failed_when: "'Metrics' not in metrics_output.content"
